# Generated by Django 6.0.3 on 2026-03-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_department_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
