# Generated by Django 6.0.3 on 2026-03-27 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_departement_department_id_and_more'),
        ('teacher', '0003_remove_subject_department_remove_subject_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='departement.departement'),
            preserve_default=False,
        ),
    ]
