# Generated by Django 6.0.3 on 2026-04-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_name_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='department',
            new_name='departement',
        ),
    ]
