# Generated by Django 6.0.3 on 2026-04-01 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parent',
            old_name='permanent_adress',
            new_name='permanent_address',
        ),
        migrations.RenameField(
            model_name='parent',
            old_name='present_adress',
            new_name='present_address',
        ),
    ]
