# Generated by Django 6.0.3 on 2026-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='departement',
            name='head_of_department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
