# Generated by Django 6.0.3 on 2026-03-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='S94iExncAtD5GUGOOr2R1hSG2h5ZZRGf', editable=False, max_length=32, unique=True),
        ),
    ]
