# Generated by Django 6.0.3 on 2026-03-27 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0007_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='h4TzQkMElxGwBwDA8vKbVUgVL2BAh0Cg', editable=False, max_length=32, unique=True),
        ),
    ]
