# Generated by Django 6.0.3 on 2026-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0011_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='oc3m2DeWP9NnEchDAxyp6iJsvk8RlSPP', editable=False, max_length=32, unique=True),
        ),
    ]
