# Generated by Django 6.0.3 on 2026-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='HXDZtgiaZ6m1JzQN2l7zBEwH8yQiNVEe', editable=False, max_length=32, unique=True),
        ),
    ]
